---
# tasks file for webserver

- name: install {{ pack_1 }}
  yum:
    name: "{{ pack_1 }}"
    state: present 

- name: start and enable server
  service:
    name: "{{ ser_1 }}"
    state: started
    enabled: yes

- name: start firewall
  firewalld:
    service: "{{rule_1}}"
    permanent: yes
    immediate: yes
    state: enabled



- name: add web page template
  template:
    src: index.j2
    dest: /var/www/html/index.html
  notify: restart_web
